import type { MuscleLevelMap, PlannerConfig, Preset } from "../types/training";

export const DEFAULT_LEVELS: MuscleLevelMap = {
  chest: 6,
  back: 8,
  lateralDelt: 7,
  biceps: 6,
  triceps: 6,
  quads: 5,
  hamstrings: 5,
  calves: 4,
};

export const DEFAULT_CONFIG: PlannerConfig = {
  levels: DEFAULT_LEVELS,
  trainingDays: 5,
  keepBalanced: true,
};

export const PRESETS: Preset[] = [
  {
    id: "balanced",
    name: "Equilibrado",
    description: "Volume parelho com leve enfase em superiores.",
    levels: {
      chest: 6,
      back: 6,
      lateralDelt: 6,
      biceps: 6,
      triceps: 6,
      quads: 6,
      hamstrings: 6,
      calves: 5,
    },
  },
  {
    id: "back-focus",
    name: "Foco em costas",
    description: "Prioriza dorsais e mantem braços como suporte.",
    levels: {
      chest: 5,
      back: 10,
      lateralDelt: 8,
      biceps: 7,
      triceps: 5,
      quads: 5,
      hamstrings: 5,
      calves: 4,
    },
  },
  {
    id: "chest-focus",
    name: "Foco em peito",
    description: "Mais series para peitoral, triceps e deltoide lateral.",
    levels: {
      chest: 10,
      back: 6,
      lateralDelt: 7,
      biceps: 5,
      triceps: 8,
      quads: 5,
      hamstrings: 5,
      calves: 4,
    },
  },
  {
    id: "arms-focus",
    name: "Foco em braços",
    description: "Especializa biceps e triceps sem abandonar compostos.",
    levels: {
      chest: 6,
      back: 6,
      lateralDelt: 7,
      biceps: 10,
      triceps: 10,
      quads: 5,
      hamstrings: 5,
      calves: 4,
    },
  },
  {
    id: "v-shape",
    name: "V-shape",
    description: "Costas largas e ombro lateral como prioridade visual.",
    levels: {
      chest: 6,
      back: 10,
      lateralDelt: 10,
      biceps: 7,
      triceps: 5,
      quads: 4,
      hamstrings: 4,
      calves: 4,
    },
  },
  {
    id: "full-body",
    name: "Full body equilibrado",
    description: "Frequencia alta, volume controlado e bom para 3 dias.",
    trainingDays: 3,
    keepBalanced: true,
    levels: {
      chest: 6,
      back: 6,
      lateralDelt: 6,
      biceps: 5,
      triceps: 5,
      quads: 6,
      hamstrings: 6,
      calves: 5,
    },
  },
  {
    id: "upper-specialization",
    name: "Especialização superiores",
    description: "Aumenta tronco e braços, pernas entram em manutencao.",
    trainingDays: 5,
    levels: {
      chest: 8,
      back: 9,
      lateralDelt: 9,
      biceps: 8,
      triceps: 8,
      quads: 4,
      hamstrings: 4,
      calves: 3,
    },
  },
];
